[build]
  functions = "src/lambda"

[dev]
  framework = "#custom"
  command = "npm run watch"
  targetPort = 8080
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/:function"
  to = "/.netlify/functions/:function"
  status = 200
