executors:
  node:
    parameters:
      image:
        type: string
        default: 'lts'
    docker:
      - image: circleci/node:<< parameters.image >>
        environment:
          TERM: xterm

aliases:
  install_node_modules: &install_node_modules
    run:
      name: Install Packages
      command: npm install

  build: &build
    run:
      name: Build Gatsby Site
      command: |
        echo -e "Working directory ${CIRCLE_WORKING_DIRECTORY}\n"
        ls -l
        npm run build

  deploy_gh_pages: &deploy_gh_pages
    deploy:
      name: Deploy to Github Pages
      command: |
        echo -e "Starting to deploy to Github Pages. Working directory ${CIRCLE_WORKING_DIRECTORY}\n"
        ls -l
        git config --global user.email ${GIT_EMAIL}
        git config --global user.name ${GIT_NAME}
        echo albertmolodec.js.org > ./public/CNAME
        ./node_modules/.bin/gh-pages -d public -b master -r https://${GH_TOKEN}@github.com/${TARGET_REPO}

  test: &test
    run:
      name: Testing
      command: npm run test

  restore_cache: &restore_cache
    restore_cache:
      name: Restore Package Cache
      keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-

  save_cache: &save_cache
    save_cache:
      name: Save Package Cache
      key: v1-dependencies-{{ checksum "package-lock.json" }}
      paths:
        - node_modules

  store_results: &store_results
    store_test_results:
      path: results

  store_results_artifacts: &store_results_artifacts
    store_artifacts:
      path: results

version: 2.1

jobs:
  build:
    executor: node
    working_directory: ~/website
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - <<: *build
  test:
    executor: test
    steps:
      - <<: *test
  deploy_gh_pages:
    executor: node
    working_directory: ~/website
    environment:
      TARGET_REPO: albertmolodec/albertmolodec.github.io.git
      GIT_EMAIL: 'albert.abdu@gmail.com'
      GIT_NAME: 'Альберт Абдульманов'
    steps:
      - <<: *deploy_gh_pages

workflows:
  version: 2
  main:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: source
              ignore:
                - master
      - deploy_gh_pages:
          requires:
            - build
          filters:
            branches:
              only: source
              ignore: master
