version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/website
    environment:
      TARGET_REPO: albertmolodec/albertmolodec.github.io.git
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Setup Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      # - run: yarn test

      - deploy:
          name: Deploy to Github Pages
          command: |
            echo -e "Starting to deploy to Github Pages\n"
            cd ~/website
            git config --global user.email "albert.abdu@gmail.com"
            git config --global user.name "Альберт Абдульманов"
            npm run build
            npm run set-cname
            ./node_modules/.bin/gh-pages -d public -b master -r https://${GH_TOKEN}@github.com/${TARGET_REPO}
