version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:lts

aliases:
  install_node_modules: &install_node_modules
    run:
      name: Install Packages
      command: yarn

  build: &build
    run:
      name: Build Gatsby Site
      command: yarn build

  # with use of https://blog.frederikring.com/articles/deploying-github-pages-circle-ci/
  deploy_gh_pages: &deploy_gh_pages
    deploy:
      name: Deploy to Github Pages
      command: |
        if [ "${CIRCLE_BRANCH}" == "${SOURCE_BRANCH}" ]; then
          echo -e "Starting to deploy to Github Pages.\nWorking directory ${CIRCLE_WORKING_DIRECTORY}\nCurrent branch ${CIRCLE_BRANCH}"

          git config --global user.email ${GIT_EMAIL}
          git config --global user.name ${GIT_NAME}
          git clone https://${GH_TOKEN}@github.com/${TARGET_REPO} out
          cd out
          git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
          git rm -rf .

          cd ..
          cp -a public/. out/.
          cp -avr .circleci out
          cd out
          echo albert.works > ./CNAME

          git add -A
          git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
          git push origin $TARGET_BRANCH

          echo -e "\n\n\nPUBLISHED to ${TARGET_BRANCH}"
        fi

  test: &test
    run:
      name: Testing
      command: yarn test

  restore_cache: &restore_cache
    restore_cache:
      name: Restore Package Cache
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-

  save_cache: &save_cache
    save_cache:
      name: Save Package Cache
      key: v1-dependencies-{{ checksum "yarn.lock" }}
      paths:
        - node_modules

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      name: Persist build to be used by deploy
      root: .
      paths:
        - yarn.lock
        - public
        - .circleci

  attach_workspace: &attach_workspace
    attach_workspace:
      name: Attach build for deploying
      at: ~/website

  # not used yed
  store_test_results: &store_test_results
    store_test_results:
      path: results

  store_artifacts: &store_artifacts
    store_artifacts:
      path: results

jobs:
  build:
    executor: node
    working_directory: ~/website
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - <<: *build
      - <<: *store_artifacts
      - <<: *persist_to_workspace

  deploy:
    executor: node
    working_directory: ~/website
    environment:
      TARGET_REPO: albertmolodec/albertmolodec.github.io.git
      SOURCE_BRANCH: source
      TARGET_BRANCH: master
      GIT_EMAIL: 'albert.abdu@gmail.com'
      GIT_NAME: 'Альберт Абдульманов'
    steps:
      - <<: *attach_workspace
      - <<: *deploy_gh_pages

  test:
    executor: node
    working_directory: ~/website
    steps:
      - checkout
      - <<: *test

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: source
      - deploy:
          requires:
            - build
      - test:
          filters:
            branches:
              only: source
